pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/DavidWinter92/cen4802.git'
            }
        }

        stage('Build') {
            steps {
                dir('Assignment3') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Assignment3') {
                    bat 'mvn test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Assignment3') {
                    bat 'docker build -t fibonacci-app .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('Assignment3') {
                    bat 'docker run --rm fibonacci-app'
                }
            }
        }
    }
}
