apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: finalproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-dockerhub-username/frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://backend-service:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: finalproject
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
